# Solr
dataverse:
  solr:
    group: solr
    root: /opt/solr
    data: /opt/solr/dvn/data
    logs: /opt/solr/server/logs
    user: solr
    version: 7.7.2
  jetty:
    requestHeaderSize: 102400

## notes - to remove after review
# 1. Set variables here as dataverse repo due to being used during post install (see below)
# at this point not sure if needed
# ./tasks/dataverse-postinstall.yml:61:  script: '/tmp/dvinstall/updateSchemaMDB.sh -t {{ dataverse.solr.root }}/server/solr/collection1/conf'


