dataverse:
  adminpass: admin1
  allow_signups: true
  api:
    allow_lookup: false
    blocked_endpoints: "admin,test"
    blocked_policy: "localhost-only"
    location: "http://localhost:8080/api"
    test_suite: false
    tests: all
  doi:
    authority: "10.5072"
    baseurl: "https://mds.test.datacite.org/"
    dataciterestapiurl: "https://api.test.datacite.org"
    mdcbaseurl: "https://api.test.datacite.org/"
    username: "testaccount"
    password: "notmypassword"
    protocol: doi
    provider: FAKE
    shoulder: "FK2/"
  payara:
    version: 5.2020.2
    group: dataverse
    user: dataverse
    root: /opt
    dir: /opt/payara5
    launch_timeout: 180
    request_timeout: 1800
    adminuser: admin
    adminpass: notPr0d
    siteUrl: 
  service_email: noreply@outgoing.mit.edu
  smtp: localhost:25 
  memheap: 2048
  srcdir: /opt
  target: /opt/dvinstall/target
  filesdirs:
    label: file
    path: /opt/dvn/data
# Filedirs for stage and prod will point to s3 sftp 
solr:
  host: solr_host
  
rserve:
  host: localhost
  user: rserve
  group: rserve
  pass: rserve
  port: 6311
  workdir: /tmp/Rserv

db:
  postgres:
    adminpass: DVn33dsth1s
    name: rdr
    host: "rds_host"
    user: dvnuser
    pass: dvnsecret
    jdbcurl: 
    version: 11
    port: 5432

postfix:
  smtp_host: "outgoing.mit.edu"
  smtp_user: "smtp_user"
  smtp_password: "smtp_password"
  smtp_port: 543
  myorigin: "mit.edu"
  mydestination: "$myhostname, localhost.$mydomain, localhost, {{ cname }}, {{ ansible_host }}"
cname: ""

install_src_version: "v5.0"
install_src: "https://github.com/IQSS/dataverse/releases/download/{{install_src_version}}/dvinstall.zip"
